export const MICROSERVICES_CLIENTS = {
  USERS: { CLIENT_NAME: 'USERS_SERVICE', PORT: 4003 },
  PRODUCT: { CLIENT_NAME: 'PRODUCT_SERVICE', PORT: 4002 },
  ORDERS: { CLIENT_NAME: 'ORDERS_SERVICE', PORT: 4001 },
};
